### ISSUE TITLE
Singularity.intel build successful | However I face the following error when running exec with singularity

### ISSUE THREAD

**Issue by finalelement** [robbert-harms/MDT#18]
sudo singularity exec mdt_image_v1 mdt-list-devices

Output Error: 
Traceback (most recent call last):
  File "/usr/bin/mdt-list-devices", line 9, in <module>
    load_entry_point('mdt==1.2.1', 'console_scripts', 'mdt-list-devices')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/mdt/__init__.py", line 8, in <module>
    import mot
  File "/usr/lib/python3/dist-packages/mot/__init__.py", line 3, in <module>
    from .optimize import minimize, get_minimizer_options
  File "/usr/lib/python3/dist-packages/mot/optimize/__init__.py", line 1, in <module>
    from mot.lib.cl_function import SimpleCLFunction
  File "/usr/lib/python3/dist-packages/mot/lib/cl_function.py", line 3, in <module>
    import tatsu
  File "/usr/local/lib/python3.5/dist-packages/tatsu/__init__.py", line 6, in <module>
    from tatsu.tool import (  # pylint: disable=W0622
  File "/usr/local/lib/python3.5/dist-packages/tatsu/tool.py", line 16, in <module>
    from tatsu.parser import GrammarGenerator
  File "/usr/local/lib/python3.5/dist-packages/tatsu/parser.py", line 4, in <module>
    from tatsu.bootstrap import EBNFBootstrapParser
  File "/usr/local/lib/python3.5/dist-packages/tatsu/bootstrap.py", line 18, in <module>
    from tatsu.buffering import Buffer
  File "/usr/local/lib/python3.5/dist-packages/tatsu/buffering.py", line 20, in <module>
    from .infos import PosLine, LineIndexInfo, LineInfo, CommentInfo
  File "/usr/local/lib/python3.5/dist-packages/tatsu/infos.py", line 6, in <module>
    from .ast import AST
  File "/usr/local/lib/python3.5/dist-packages/tatsu/ast.py", line 73
    f'{type(self).__name__} attributes are fixed. '

**Comment by robbert-harms** [comment]
Hi,

I looked into this issue and the problem is that the latest version of Tatsu only supports Python 3.8 or higher. Since this is not the Python version used by default in Ubuntu 16.04, the installation fails.

A workaround is to specify the exact version of Tatsu to install in the Singularity container. In the file Singularity.intel, if you change the last line from:

```
pip3 install tatsu
```

to

```
pip3 install tatsu==4.2.6
```

After that, you will of course have to reinstall the Singularity image. You can have a look at the latest master branch, I made the changes already.

Please let me know if this fixes the issue for you.

With best wishes,

Robbert

**Comment by finalelement** [comment]
Dr. Harms,

Thank you for such a quick response. Ill try rebuilding the singularity
with the changes made for the tatsu version.

Also, out of curiosity since you've made models like AxCaliber and Verdict
possible for quick processing on HCP Data a few hours (GPU-based) versus
the many hours on (CPU-based). Were the measures computed found to be
insightful and reliable on the HCP data ?

Thanks,
Vish

**Comment by finalelement** [comment]
I tried out the new singularity build with the downgraded version of tatsu:
Installing collected packages: tatsu
Successfully installed tatsu-4.2.6

After which I faced a new error:
The below error seems to be coming 'mot' and 'pyopencl':
nathv@masi-19:/nfs/masi/nathv/mdt_singularity$ sudo singularity exec mdt_image_v1 mdt-list-devices
Traceback (most recent call last):
  File "/usr/bin/mdt-list-devices", line 9, in <module>
    load_entry_point('mdt==1.2.1', 'console_scripts', 'mdt-list-devices')()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python3/dist-packages/mdt/__init__.py", line 8, in <module>
    import mot
  File "/usr/lib/python3/dist-packages/mot/__init__.py", line 3, in <module>
    from .optimize import minimize, get_minimizer_options
  File "/usr/lib/python3/dist-packages/mot/optimize/__init__.py", line 1, in <module>
    from mot.lib.cl_function import SimpleCLFunction
  File "/usr/lib/python3/dist-packages/mot/lib/cl_function.py", line 6, in <module>
    from mot.configuration import CLRuntimeInfo
  File "/usr/lib/python3/dist-packages/mot/configuration.py", line 20, in <module>
    from .lib.cl_environments import CLEnvironmentFactory
  File "/usr/lib/python3/dist-packages/mot/lib/cl_environments.py", line 172, in <module>
    _cl_environment_cache = _initialize_cl_environment_cache()
  File "/usr/lib/python3/dist-packages/mot/lib/cl_environments.py", line 162, in _initialize_cl_environment_cache
    context = cl.Context(devices)
pyopencl.LogicError: Context failed: invalid value

**Comment by robbert-harms** [comment]
Hi,

I apologize, I should have tested the Singularity container myself. On my new computer I had yet to configure singularity and thought a quick fix would solve the problems.

There was unfortunately yet another problem, this time indeed with MOT (the primary dependency of MDT). I fixed this issue as well and tested the singularity image. This time mdt-list-devices runs fine.

Let me know if this also solves the problem for you now.

Best wishes,

Robbert

**Comment by finalelement** [comment]
Dr. Harms,

That's great news. I'll test it out tomorrow and let you know how it goes.

Again, thank you for support and quick turnarounds.

Best wishes,
Vish

**Comment by finalelement** [comment]
I don't see changes to the singularity recipe though, was this fix applied
on the mot library or something like that?

Thanks,
Vish

**Comment by robbert-harms** [comment]
Changes were applied to the MOT library, this is indeed not reflected in the Singularity container.

In the current set-up, the singularity container tracks the latest version of MDT. Perhaps I should change that to point to a fixed version in the future, but that is something for later thought.

**Comment by finalelement** [comment]
Hello Dr. Harms,

I have some good news and bad news. The good news is that after building the singularity it does function and detect the device of CPU. For e.g below:
nathv@masi-19:/nfs/masi/nathv/mdt_singularity$ sudo singularity exec mdt_single_image mdt-list-devices
[sudo] password for nathv: 
Device 0:
CPU - Intel(R) Xeon(R) CPU E5-1620 v3 @ 3.50GHz (Intel(R) OpenCL)

Bad news: It does not detect the GPU. I have two GPU's on my machine and both function and I often use the bigger one for deep learning stuff. Is it expected behaviour for mdt-list-devices to not show GPU's?

These are the two GPU's that I have, output of nvidia-smi:
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  Quadro K620         Off  | 00000000:03:00.0  On |                  N/A |
| 39%   53C    P0     4W /  30W |    950MiB /  1994MiB |      0%      Default |
+-------------------------------+----------------------+----------------------+
|   1  GeForce GTX 108...  Off  | 00000000:04:00.0 Off |                  N/A |
| 29%   27C    P8     8W / 250W |      2MiB / 11178MiB |      0%      Default

**Comment by robbert-harms** [comment]
This was to be expected actually. The provided Singular container only offers an Intel CPU driver. 

At the time I created those containers there was no easy way to forward a GPU inside the container, that is why I only created CPU containers. 

There are two things you can do:

1) Create a new Singularity container and encapsulate the AMD or Nvidia drivers, for example as shown here: https://sylabs.io/guides/3.5/user-guide/gpu.html#opencl-applications

2) Install MDT locally on your system without a container.

In any case, mdt-list-devices will show GPU's when it can find and use them.

Best wishes,

Robbert

**Comment by finalelement** [comment]
Thank you for the amazing support Dr. Harms. I think all my queries are resolved.

Thanks a ton,
Vish
